spring.datasource.url=jdbc:h2:mem:agendador;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT (ambiente local)
# IMPORTANTE: em produção, use segredo via variável de ambiente / cofre seguro.
security.jwt.secret=U3VwZXJTZWdyZWRvRGV2QWdlbmRhZG9ySG9yYXJpb3MyMDI2Q29tMzJCeXRlcw==
security.jwt.expiration-seconds=900
